version: 2.1

orbs:
  mirci: libmir/upload_docs@0.0.0

jobs:
  build:
    docker:
      - image: libmir/circle-dlang
    steps:
      - checkout
      - run: git submodule sync && git submodule update --recursive --init
      # - run: dub test
      # - run: dub test -c dips
      - run: meson build -D with_tests=true
      - run: ninja -C build test
      - run: make -f doc/Makefile html
      - mirci/persist_docs:
          from: web

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - mirci/upload_docs_job:
          from: web
          to: mir-algorithm.libmir.org
          requires:
            - build
          filters:
            branches:
              only: master
