version: 2.1

orbs:
  mirci: libmir/upload_docs@0.0.0

jobs:
  build:
    docker:
      - image: libmir/circle-dlang
    steps:
      - checkout
      - run: cp /docgen docgen && cp//web web
      - run: meson build
      - run: ninja -C build test
      - mirci/persist_docs:
          from: web

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - mirci/upload_docs_job:
          from: web
          to: mir-algorithm.libmir.org
          requires:
            - build
          filters:
            branches:
              only: master
